/** App-level route identifiers for the consumer web app. */
export type AppRoute =
  | 'map'
  | 'ranks'
  | 'feed'
  | 'friends'
  | 'profile'
  | 'settings'
  | 'privacy'
  | 'notifications'
  | 'notification-settings'
  | 'history'
  | 'login'
  | 'forgot-password'
  | 'landing'
  | 'first-get-prompt'
  | 'legal-privacy'
  | 'legal-terms'
