/**
 * Operator-side render visibility property test.
 *
 * Property 8 — Render visibility: operator hides snapshots.
 *
 * **Validates: Requirements 6.6, 7.6**
 *
 * The operator-facing `BoostPurchasesPanel` MUST NOT leak snapshot fields
 * intended for ops/admin only:
 *   - `tierSnapshot`
 *   - `neighbourhoodIdSnapshot`
 *   - `floorAtPurchaseCents`
 *
 * This test renders the panel with arbitrary rows generated by `fast-check`,
 * deliberately ALSO returning the snapshot fields from the mocked API to
 * defend against a future regression where the server starts leaking them
 * — the panel must not render their key names or values regardless.
 */
// @vitest-environment jsdom
import { render, cleanup, waitFor } from '@testing-library/react'
import * as fc from 'fast-check'
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest'

// ─── Mocks ────────────────────────────────────────────────────────────────────

// react-i18next: stable identity so useEffect dependencies do not re-fire on
// every render of the SUT.
vi.mock('react-i18next', () => {
  const t = (_key: string, fallback?: string) => fallback ?? _key
  return { useTranslation: () => ({ t }) }
})

const apiGet = vi.fn()
vi.mock('@area-code/shared/lib/api', () => ({
  api: {
    get: (...args: unknown[]) => apiGet(...args),
    post: vi.fn(),
    put: vi.fn(),
    patch: vi.fn(),
    delete: vi.fn(),
    setTokenProvider: vi.fn(),
    setRefreshHandler: vi.fn(),
    setRefreshPath: vi.fn(),
    ensureValidToken: vi.fn().mockResolvedValue(null),
  },
}))

// Auth store: provide a stable businessId so the panel kicks off its fetch.
vi.mock('@area-code/shared/stores/businessAuthStore', () => ({
  useBusinessAuthStore: (selector: (s: { businessId: string | null }) => unknown) =>
    selector({ businessId: 'biz-test-1' }),
}))

// Business store: empty nodes list — the panel falls back to the raw nodeId
// for unresolved nodes, which keeps the rendered DOM deterministic.
vi.mock('@area-code/shared/stores/businessStore', () => ({
  useBusinessStore: (selector: (s: { nodes: Array<{ id: string; name: string }> }) => unknown) =>
    selector({ nodes: [] }),
}))

// Import AFTER vi.mock calls so the panel resolves to the mocked modules.
import { BoostPurchasesPanel } from '../components/BoostPurchasesPanel'

// ─── Arbitraries ──────────────────────────────────────────────────────────────

const durationArb = fc.constantFrom('2hr', '6hr', '24hr') as fc.Arbitrary<'2hr' | '6hr' | '24hr'>

const tierArb = fc.constantFrom('starter', 'growth', 'pro', 'payg') as fc.Arbitrary<
  'starter' | 'growth' | 'pro' | 'payg'
>

/** Restricted alphanumeric id — keeps generated strings printable and
 *  detectable in the DOM. */
const idCharsArb = fc.string({
  minLength: 1,
  maxLength: 24,
  unit: fc.constantFrom(...'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_'.split('')),
})

/** ISO-8601 millisecond-precision UTC, drawn from a wide but valid window so
 *  `formatPaidAt` always produces a fixed-shape output. */
const paidAtArb = fc
  .integer({ min: Date.UTC(2024, 0, 1), max: Date.UTC(2030, 11, 31) })
  .map((ms) => new Date(ms).toISOString())

/** Operator-facing `BoosterPurchaseView` shape. The panel is the SUT, so we
 *  also inject the three snapshot fields we expect NOT to be rendered, to
 *  guard against a future server-side leak. */
interface LeakyRow {
  businessId: string
  nodeId: string
  duration: '2hr' | '6hr' | '24hr'
  amountCents: number
  currency: 'ZAR'
  yocoCheckoutId: string
  paidAt: string
  // Forbidden fields — present in the API response shape only to verify
  // the panel never surfaces them.
  tierSnapshot: 'starter' | 'growth' | 'pro' | 'payg'
  neighbourhoodIdSnapshot: string | null
  floorAtPurchaseCents: number
}

const leakyRowArb: fc.Arbitrary<LeakyRow> = fc.record({
  businessId: fc.constant('biz-test-1'),
  nodeId: idCharsArb,
  duration: durationArb,
  amountCents: fc.integer({ min: 1, max: 1_000_000 }),
  currency: fc.constant('ZAR' as const),
  yocoCheckoutId: idCharsArb,
  paidAt: paidAtArb,
  tierSnapshot: tierArb,
  neighbourhoodIdSnapshot: fc.option(idCharsArb, { nil: null }),
  floorAtPurchaseCents: fc.integer({ min: 1, max: 1_000_000 }),
})

// ─── Test ─────────────────────────────────────────────────────────────────────

beforeEach(() => {
  apiGet.mockReset()
})

afterEach(() => {
  cleanup()
})

describe('BoostPurchasesPanel — operator render visibility (Property 8)', () => {
  it('never renders tierSnapshot, neighbourhoodIdSnapshot, or floorAtPurchaseCents key names or values', async () => {
    await fc.assert(
      fc.asyncProperty(leakyRowArb, async (row) => {
        // Reset the API mock per run and resolve with a single-row page so
        // the panel transitions into its rendered state.
        apiGet.mockReset()
        apiGet.mockResolvedValue({ items: [row], nextCursor: null })

        const { container, unmount } = render(<BoostPurchasesPanel />)

        // Wait for the row to appear (the panel formats `paidAt` into the
        // displayed string, so we wait on the duration cell which is rendered
        // verbatim and is always present once the fetch resolves).
        await waitFor(() => {
          expect(container.textContent ?? '').toContain(row.duration)
        })

        const text = container.textContent ?? ''

        // R6.6 / R7.6 — the operator panel MUST NOT leak the key names of
        // any of the three forbidden snapshot fields. A leak typically
        // surfaces either as an explicit label (e.g. `Tier: starter`) or
        // as the raw JSON-stringified row dumped into the DOM — both of
        // which would contain these literal substrings (case-insensitive).
        expect(text).not.toMatch(/tierSnapshot/i)
        expect(text).not.toMatch(/neighbourhoodIdSnapshot/i)
        expect(text).not.toMatch(/floorAtPurchaseCents/i)

        unmount()
      }),
      { numRuns: 50 },
    )
  })
})
