export { api, type ApiError } from './api'
export { getSocket, disconnectSocket } from './socket'
export { storage } from './storage'
export { isWeb, setPageTitle, getDeviceInfo, isOnline, isSaveDataEnabled, hasGeolocation, getCurrentPosition } from './platform'
export { haversineDistance, isWithinRadius } from './geoUtils'
export { formatZAR, formatRelativeTime, formatLocalTime, formatLocalDate, formatCountdown, toE164 } from './formatters'
export * from './featureGating'
export { computeDimensionScores, resolveArchetype, matchesArchetype } from './archetypeResolver'
