/**
 * Dev-only mock venue data.
 *
 * This module is imported solely behind `DEV_MODE` guards in the nodes service.
 * It never runs in production (see `no-fallbacks-no-legacy.md`). The set spans
 * all nine South African provinces plus a handful of global sites so the dev
 * map can be exercised anywhere in the world, not just Johannesburg.
 *
 * pulseScore / state here are static fixtures for local UI work only. They are
 * NOT an honest live signal (see `honest-presence.md`); real presence is always
 * backed by check-in + expiry over the live path in prod.
 */

export interface DevNode {
  id: string
  name: string
  slug: string
  category: string
  lat: number
  lng: number
  pulseScore: number
  state: string
  citySlug: string
  cityName: string
}

export const DEV_NODES: DevNode[] = [
  // ─── Gauteng · Johannesburg ───────────────────────────────────────────────
  {
    id: 'dev-1',
    name: 'Father Coffee',
    slug: 'father-coffee',
    category: 'coffee',
    lat: -26.1834,
    lng: 28.0172,
    pulseScore: 8,
    state: 'quiet',
    citySlug: 'johannesburg',
    cityName: 'Johannesburg',
  },
  {
    id: 'dev-2',
    name: 'Doubleshot Coffee',
    slug: 'doubleshot-coffee',
    category: 'coffee',
    lat: -26.1838,
    lng: 28.0168,
    pulseScore: 0,
    state: 'dormant',
    citySlug: 'johannesburg',
    cityName: 'Johannesburg',
  },
  {
    id: 'dev-3',
    name: "Kitchener's Bar",
    slug: 'kitcheners-bar',
    category: 'nightlife',
    lat: -26.1931,
    lng: 28.0348,
    pulseScore: 72,
    state: 'popping',
    citySlug: 'johannesburg',
    cityName: 'Johannesburg',
  },
  {
    id: 'dev-4',
    name: 'Taboo Nightclub',
    slug: 'taboo-nightclub',
    category: 'nightlife',
    lat: -26.1085,
    lng: 28.0572,
    pulseScore: 65,
    state: 'popping',
    citySlug: 'johannesburg',
    cityName: 'Johannesburg',
  },
  {
    id: 'dev-5',
    name: 'Sandton City',
    slug: 'sandton-city',
    category: 'shopping',
    lat: -26.1073,
    lng: 28.052,
    pulseScore: 18,
    state: 'active',
    citySlug: 'johannesburg',
    cityName: 'Johannesburg',
  },
  {
    id: 'dev-6',
    name: 'Arts on Main',
    slug: 'arts-on-main',
    category: 'culture',
    lat: -26.2048,
    lng: 28.0565,
    pulseScore: 55,
    state: 'buzzing',
    citySlug: 'johannesburg',
    cityName: 'Johannesburg',
  },
  {
    id: 'dev-7',
    name: "Nando's Rosebank",
    slug: 'nandos-rosebank',
    category: 'food',
    lat: -26.14565,
    lng: 28.04325,
    pulseScore: 45,
    state: 'buzzing',
    citySlug: 'johannesburg',
    cityName: 'Johannesburg',
  },
  {
    id: 'dev-8',
    name: 'Neighbourgoods Market',
    slug: 'neighbourgoods-market',
    category: 'food',
    lat: -26.1925,
    lng: 28.0335,
    pulseScore: 25,
    state: 'active',
    citySlug: 'johannesburg',
    cityName: 'Johannesburg',
  },
  {
    id: 'dev-9',
    name: 'The Grillhouse',
    slug: 'the-grillhouse',
    category: 'food',
    lat: -26.1468,
    lng: 28.0418,
    pulseScore: 38,
    state: 'buzzing',
    citySlug: 'johannesburg',
    cityName: 'Johannesburg',
  },
  {
    id: 'dev-10',
    name: 'Virgin Active Sandton',
    slug: 'virgin-active-sandton',
    category: 'fitness',
    lat: -26.1068,
    lng: 28.0528,
    pulseScore: 3,
    state: 'quiet',
    citySlug: 'johannesburg',
    cityName: 'Johannesburg',
  },
  {
    id: 'dev-11',
    name: 'Planet Fitness Melrose',
    slug: 'planet-fitness-melrose',
    category: 'fitness',
    lat: -26.1345,
    lng: 28.0685,
    pulseScore: 5,
    state: 'quiet',
    citySlug: 'johannesburg',
    cityName: 'Johannesburg',
  },
  {
    id: 'dev-12',
    name: 'Keyes Art Mile',
    slug: 'keyes-art-mile',
    category: 'culture',
    lat: -26.1492,
    lng: 28.0408,
    pulseScore: 12,
    state: 'active',
    citySlug: 'johannesburg',
    cityName: 'Johannesburg',
  },

  // ─── Gauteng · Pretoria ───────────────────────────────────────────────────
  {
    id: 'dev-20',
    name: 'Menlyn Park',
    slug: 'menlyn-park',
    category: 'shopping',
    lat: -25.7846,
    lng: 28.2775,
    pulseScore: 30,
    state: 'active',
    citySlug: 'pretoria',
    cityName: 'Pretoria',
  },
  {
    id: 'dev-21',
    name: 'Capital Craft',
    slug: 'capital-craft',
    category: 'nightlife',
    lat: -25.7712,
    lng: 28.2769,
    pulseScore: 58,
    state: 'buzzing',
    citySlug: 'pretoria',
    cityName: 'Pretoria',
  },
  {
    id: 'dev-22',
    name: 'Hazel Food Market',
    slug: 'hazel-food-market',
    category: 'food',
    lat: -25.7625,
    lng: 28.2588,
    pulseScore: 22,
    state: 'active',
    citySlug: 'pretoria',
    cityName: 'Pretoria',
  },

  // ─── Western Cape · Cape Town ─────────────────────────────────────────────
  {
    id: 'dev-30',
    name: 'Truth Coffee',
    slug: 'truth-coffee',
    category: 'coffee',
    lat: -33.9271,
    lng: 18.4249,
    pulseScore: 40,
    state: 'buzzing',
    citySlug: 'cape-town',
    cityName: 'Cape Town',
  },
  {
    id: 'dev-31',
    name: 'The Gin Bar',
    slug: 'the-gin-bar',
    category: 'nightlife',
    lat: -33.9258,
    lng: 18.4187,
    pulseScore: 63,
    state: 'popping',
    citySlug: 'cape-town',
    cityName: 'Cape Town',
  },
  {
    id: 'dev-32',
    name: 'V&A Waterfront',
    slug: 'va-waterfront',
    category: 'shopping',
    lat: -33.9036,
    lng: 18.4207,
    pulseScore: 35,
    state: 'buzzing',
    citySlug: 'cape-town',
    cityName: 'Cape Town',
  },
  {
    id: 'dev-33',
    name: 'Zeitz MOCAA',
    slug: 'zeitz-mocaa',
    category: 'culture',
    lat: -33.9076,
    lng: 18.4231,
    pulseScore: 28,
    state: 'active',
    citySlug: 'cape-town',
    cityName: 'Cape Town',
  },

  // ─── KwaZulu-Natal · Durban ───────────────────────────────────────────────
  {
    id: 'dev-40',
    name: 'Circus Circus Beach Cafe',
    slug: 'circus-circus-beach-cafe',
    category: 'food',
    lat: -29.8074,
    lng: 31.0409,
    pulseScore: 33,
    state: 'buzzing',
    citySlug: 'durban',
    cityName: 'Durban',
  },
  {
    id: 'dev-41',
    name: 'Origin Coffee Roasting',
    slug: 'origin-coffee-durban',
    category: 'coffee',
    lat: -29.8489,
    lng: 31.0219,
    pulseScore: 10,
    state: 'quiet',
    citySlug: 'durban',
    cityName: 'Durban',
  },
  {
    id: 'dev-42',
    name: 'Gateway Theatre of Shopping',
    slug: 'gateway-theatre',
    category: 'shopping',
    lat: -29.7256,
    lng: 31.0662,
    pulseScore: 27,
    state: 'active',
    citySlug: 'durban',
    cityName: 'Durban',
  },

  // ─── Eastern Cape · Gqeberha ──────────────────────────────────────────────
  {
    id: 'dev-50',
    name: 'Boardwalk Casino',
    slug: 'boardwalk-casino',
    category: 'nightlife',
    lat: -33.9846,
    lng: 25.6673,
    pulseScore: 48,
    state: 'buzzing',
    citySlug: 'gqeberha',
    cityName: 'Gqeberha',
  },
  {
    id: 'dev-51',
    name: 'Vovo Telo Bakery',
    slug: 'vovo-telo',
    category: 'coffee',
    lat: -33.9789,
    lng: 25.6539,
    pulseScore: 9,
    state: 'quiet',
    citySlug: 'gqeberha',
    cityName: 'Gqeberha',
  },

  // ─── Free State · Bloemfontein ────────────────────────────────────────────
  {
    id: 'dev-60',
    name: 'Mystic Boer',
    slug: 'mystic-boer',
    category: 'nightlife',
    lat: -29.1183,
    lng: 26.2249,
    pulseScore: 44,
    state: 'buzzing',
    citySlug: 'bloemfontein',
    cityName: 'Bloemfontein',
  },
  {
    id: 'dev-61',
    name: 'Loch Logan Waterfront',
    slug: 'loch-logan-waterfront',
    category: 'shopping',
    lat: -29.1215,
    lng: 26.2076,
    pulseScore: 16,
    state: 'active',
    citySlug: 'bloemfontein',
    cityName: 'Bloemfontein',
  },

  // ─── Mpumalanga · Mbombela ────────────────────────────────────────────────
  {
    id: 'dev-70',
    name: 'Ilanga Mall',
    slug: 'ilanga-mall',
    category: 'shopping',
    lat: -25.4557,
    lng: 30.9702,
    pulseScore: 14,
    state: 'active',
    citySlug: 'mbombela',
    cityName: 'Mbombela',
  },
  {
    id: 'dev-71',
    name: 'Mediterranean Coffee',
    slug: 'mediterranean-coffee',
    category: 'coffee',
    lat: -25.4713,
    lng: 30.9756,
    pulseScore: 6,
    state: 'quiet',
    citySlug: 'mbombela',
    cityName: 'Mbombela',
  },

  // ─── Limpopo · Polokwane ──────────────────────────────────────────────────
  {
    id: 'dev-80',
    name: 'Mall of the North',
    slug: 'mall-of-the-north',
    category: 'shopping',
    lat: -23.8464,
    lng: 29.4645,
    pulseScore: 19,
    state: 'active',
    citySlug: 'polokwane',
    cityName: 'Polokwane',
  },
  {
    id: 'dev-81',
    name: 'Cafe Pavilion',
    slug: 'cafe-pavilion',
    category: 'food',
    lat: -23.9008,
    lng: 29.4525,
    pulseScore: 11,
    state: 'active',
    citySlug: 'polokwane',
    cityName: 'Polokwane',
  },

  // ─── North West · Rustenburg ──────────────────────────────────────────────
  {
    id: 'dev-90',
    name: 'Waterfall Mall',
    slug: 'waterfall-mall',
    category: 'shopping',
    lat: -25.6841,
    lng: 27.2559,
    pulseScore: 13,
    state: 'active',
    citySlug: 'rustenburg',
    cityName: 'Rustenburg',
  },

  // ─── Northern Cape · Kimberley ────────────────────────────────────────────
  {
    id: 'dev-100',
    name: 'The Big Hole',
    slug: 'the-big-hole',
    category: 'culture',
    lat: -28.7411,
    lng: 24.7628,
    pulseScore: 7,
    state: 'quiet',
    citySlug: 'kimberley',
    cityName: 'Kimberley',
  },

  // ─── Global sites ─────────────────────────────────────────────────────────
  {
    id: 'dev-200',
    name: 'Ministry of Sound',
    slug: 'ministry-of-sound',
    category: 'nightlife',
    lat: 51.4952,
    lng: -0.0997,
    pulseScore: 70,
    state: 'popping',
    citySlug: 'london',
    cityName: 'London',
  },
  {
    id: 'dev-201',
    name: 'Blue Note Jazz Club',
    slug: 'blue-note-jazz-club',
    category: 'nightlife',
    lat: 40.7308,
    lng: -74.0006,
    pulseScore: 61,
    state: 'popping',
    citySlug: 'new-york',
    cityName: 'New York',
  },
  {
    id: 'dev-202',
    name: 'Golden Gai',
    slug: 'golden-gai',
    category: 'nightlife',
    lat: 35.6939,
    lng: 139.7047,
    pulseScore: 52,
    state: 'buzzing',
    citySlug: 'tokyo',
    cityName: 'Tokyo',
  },
  {
    id: 'dev-203',
    name: 'Opera Bar',
    slug: 'opera-bar',
    category: 'nightlife',
    lat: -33.8571,
    lng: 151.2151,
    pulseScore: 47,
    state: 'buzzing',
    citySlug: 'sydney',
    cityName: 'Sydney',
  },
  {
    id: 'dev-204',
    name: 'Rio Scenarium',
    slug: 'rio-scenarium',
    category: 'culture',
    lat: -22.9053,
    lng: -43.1811,
    pulseScore: 50,
    state: 'buzzing',
    citySlug: 'rio-de-janeiro',
    cityName: 'Rio de Janeiro',
  },
  {
    id: 'dev-205',
    name: 'Java House Nairobi',
    slug: 'java-house-nairobi',
    category: 'coffee',
    lat: -1.2833,
    lng: 36.8172,
    pulseScore: 21,
    state: 'active',
    citySlug: 'nairobi',
    cityName: 'Nairobi',
  },
  {
    id: 'dev-206',
    name: 'The Dubai Mall',
    slug: 'the-dubai-mall',
    category: 'shopping',
    lat: 25.1972,
    lng: 55.2796,
    pulseScore: 42,
    state: 'buzzing',
    citySlug: 'dubai',
    cityName: 'Dubai',
  },
  {
    id: 'dev-207',
    name: 'Le Comptoir General',
    slug: 'le-comptoir-general',
    category: 'nightlife',
    lat: 48.8712,
    lng: 2.3676,
    pulseScore: 39,
    state: 'buzzing',
    citySlug: 'paris',
    cityName: 'Paris',
  },
  {
    id: 'dev-208',
    name: 'Terrazza Borromini',
    slug: 'terrazza-borromini',
    category: 'nightlife',
    lat: 41.8992,
    lng: 12.4731,
    pulseScore: 46,
    state: 'buzzing',
    citySlug: 'rome',
    cityName: 'Rome',
  },
]
